# --- Main Bedroom: ZHA Switch Toggles ---
- id: 'main_bedroom_light_1_toggle'
  alias: 'Main Bedroom Light 1 Toggle'
  description: 'Toggles the main bedroom light from the first ZHA switch button.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 'ecb5dfb90a50493454264063d9090ca7'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.main_bedroom_light
  mode: single

- id: 'main_bedroom_light_2_toggle'
  alias: 'Main Bedroom Light 2 Toggle'
  description: 'Toggles the main bedroom lights from the second ZHA switch button.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 'ecb5dfb90a50493454264063d9090ca7'
        command: '2_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.main_bedroom_lights
  mode: single

# --- Secondary Bedroom: ZHA Switch Toggles ---
- id: 'secondary_bedroom_light_1_toggle'
  alias: 'Secondary Bedroom Light 1 Toggle'
  description: 'Toggles the secondary bedroom light from the first ZHA switch.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '65322570e3d5261e9c554508a15a1b42'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.secondary_bedroom_light
  mode: single

- id: 'secondary_bedroom_light_2_toggle'
  alias: 'Secondary Bedroom Light 2 Toggle'
  description: 'Toggles the secondary bedroom light from another ZHA switch.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: 'f2e7fe4b71f5f4f8c8e14104052b76cd'
        command: 'single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.secondary_bedroom_light
  mode: single

# --- Tertiary Bedroom: ZHA Switch Toggles ---
- id: 'tertiary_bedroom_light_1_toggle'
  alias: 'Tertiary Bedroom Light 1 Toggle'
  description: 'Toggles the tertiary bedroom light from the first ZHA switch.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '587844ccda8e9aac2554807e19738209'
        command: '1_single'
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '587844ccda8e9aac2554807e19738209'
        command: '2_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.tertiary_bedroom_light
  mode: single

# - id: 'tertiary_bedroom_light_2_toggle'
#   alias: 'Tertiary Bedroom Light 2 Toggle'
#   description: 'Toggles the tertiary bedroom light from another ZHA switch.'
#   trigger:
#     - platform: event
#       event_type: zha_event
#       event_data:
#         device_id: '45a2731ba769d45c388408a8bfec3b92'
#         command: '1_single'
#   action:
#     - service: switch.toggle
#       target:
#         entity_id: switch.tertiary_bedroom_light
#   mode: single

# --- Kitchen: ZHA Switch Toggle ---
- id: 'kitchen_lights_toggle'
  alias: 'Kitchen Lights Toggle'
  description: 'Toggles the kitchen lights from a ZHA switch.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '0da9d20c7a0fd3bae7bdff68bcf2487a'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.kitchen_lights
  mode: single

# --- Toilet: ZHA Switch Toggle ---
- id: 'toilet_lights_toggle'
  alias: 'Toilet Lights Toggle'
  description: 'Toggles the toilet lights from a ZHA switch.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '3019dee32017b75a30309e7ee4983b06'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.toilet_lights
  mode: single

# --- Bathroom: Toggles & Automation ---
# - id: 'bathroom_fan_toggle'
#   alias: 'Bathroom Fan Toggle'
#   description: 'Toggles the bathroom fan from ZHA switch.'
#   trigger:
#     - platform: event
#       event_type: zha_event
#       event_data:
#         device_id: '587844ccda8e9aac2554807e19738209'
#         command: '1_single'
#   action:
#     - service: switch.toggle
#       target:
#         entity_id: switch.bathroom_fan
#   mode: single

- id: 'bathroom_lights_and_mirror_toggle'
  alias: 'Bathroom Lights and Mirror Toggle'
  description: 'Toggles bathroom lights and syncs the mirror light.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '45a2731ba769d45c388408a8bfec3b92'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.bathroom_lights
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ is_state('switch.bathroom_lights', 'off') }}"
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.bathroom_mirror_light
      default:
        - service: switch.turn_off
          target:
            entity_id: switch.bathroom_mirror_light

# --- Living & Dining Room: ZHA Switch Toggles ---
- id: 'living_dining_lights_toggle'
  alias: 'Living and Dining Lights Toggle'
  description: 'Toggles living room light and syncs the dining room light from ZHA switches.'
  trigger:
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '2396578dfa55322d4f9e545d8926c6d3'
        command: 'single'
    - platform: event
      event_type: zha_event
      event_data:
        device_id: '773211f874b927af7beb146e6ac681d1'
        command: '1_single'
  action:
    - service: switch.toggle
      target:
        entity_id: switch.living_room_light
    - choose:
        - conditions:
            - condition: state
              entity_id: 'switch.living_room_light'
              state: 'on'
          sequence:
            - service: switch.turn_on
              target:
                entity_id: switch.dining_room_light
      default:
        - service: switch.turn_off
          target:
            entity_id: switch.dining_room_light
  mode: single

# --- Hallway & Staircase: 4 Button Toggle Automation ---
- id: cfe23816e7c1a5f8996620676a4f96ab
  alias: 4 Button Smart Toggle Automation
  description: 'Smart toggle for the fourth button.'
  triggers:
  - event_type: zha_event
    event_data:
      device_id: cfe23816e7c1a5f8996620676a4f96ab
    trigger: event
  - event_type: zha_event
    event_data:
      device_id: 8980f3ebdaf1c083396f2162674fc503
    trigger: event
  actions:
  - choose:
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 1 }}'
      sequence:
      - target:
          entity_id: switch.upper_hallway_light_a
        action: switch.toggle
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 2 }}'
      sequence:
      - target:
          entity_id: switch.upper_hallway_light_b
        action: switch.toggle
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 3 }}'
      sequence:
      - target:
          entity_id: switch.staircase_lights
        action: switch.toggle
        data: {}
    - conditions:
      - condition: template
        value_template: '{{ trigger.event.data.endpoint_id == 4 }}'
      sequence:
      - choose:
        - conditions:
          - condition: or
            conditions:
            - '{{ is_state("switch.upper_hallway_light_a", "on") }}'
            - '{{ is_state("switch.upper_hallway_light_b", "on") }}'
            - '{{ is_state("switch.staircase_lights", "on") }}'
          sequence:
          - service: switch.turn_off
            target:
              entity_id:
              - switch.upper_hallway_light_a
              - switch.upper_hallway_light_b
              - switch.staircase_lights
        default:
          - service: switch.turn_on
            target:
              entity_id:
              - switch.upper_hallway_light_a
              - switch.upper_hallway_light_b
              - switch.staircase_lights
  mode: single

# --- Automatic Turn Off Automations  ---
- id: auto_bathroom_fan
  alias: Auto on Bathroom Fan
  description: 'Automatically turns on the bathroom fan when humidity rises above 80%.'
  triggers:
  - entity_id:
    - sensor.lumi_lumi_weather_humidity
    above: 80
    id: humidity_high
    trigger: numeric_state
  actions:
  - choose:
    - conditions:
      - condition: device
        type: is_off
        device_id: bdb8e97f58ef83e2c04b622334b73ea9
        entity_id: 92a6b63bb20e5bf28c38ce0cccbc8f7a
        domain: switch
      sequence:
      - type: turn_on
        device_id: bdb8e97f58ef83e2c04b622334b73ea9
        entity_id: 92a6b63bb20e5bf28c38ce0cccbc8f7a
        domain: switch

- id: auto_hallway_lights_a_b_c
  alias: Auto off Hallway Lights A,B,C
  description: 'Turns off hallway lights A, B, and C if they have been on for 3 hours.'
  triggers:
  - type: turned_on
    device_id: 22584d5e1e63d31c28f16a500eeb0474
    entity_id: 574179a0920e2787ec708798567cf302
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  - type: turned_on
    device_id: 5d45db2e944d0d9a54b75c0186098d31
    entity_id: 21a13db252f3e26795bf1cc97adfc5bf
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  - type: changed_states
    device_id: e0ee82cde043b77472155fc765589e7b
    entity_id: 21431abf5946691cf69db70e1860fbbc
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  actions:
  - type: turn_off
    device_id: 22584d5e1e63d31c28f16a500eeb0474
    entity_id: 574179a0920e2787ec708798567cf302
    domain: switch
  - type: turn_off
    device_id: 5d45db2e944d0d9a54b75c0186098d31
    entity_id: 21a13db252f3e26795bf1cc97adfc5bf
    domain: switch
  - type: turn_off
    device_id: e0ee82cde043b77472155fc765589e7b
    entity_id: 21431abf5946691cf69db70e1860fbbc
    domain: switch
  mode: single

- id: auto_kitchen_lights
  alias: Auto off Kitchen Lights
  description: 'Turns off kitchen lights if they have been on for 3 hours.'
  triggers:
  - type: changed_states
    device_id: 2d2ea827d21c3efebd62190e4eb2f047
    entity_id: 9eca8969d9b32c5ff7e4692e4155bce1
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  actions:
  - type: turn_off
    device_id: 2d2ea827d21c3efebd62190e4eb2f047
    entity_id: 9eca8969d9b32c5ff7e4692e4155bce1
    domain: switch
  mode: single

- id: auto_toilet_lights
  alias: Auto off Toilet Lights
  description: 'Turns off toilet lights if they have been on for 3 hours.'
  triggers:
  - type: turned_on
    device_id: 459adb708ca058398945d28447929b23
    entity_id: 28fa5a224616ac6e856d98b8b758d762
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  actions:
  - type: turn_off
    device_id: 459adb708ca058398945d28447929b23
    entity_id: 28fa5a224616ac6e856d98b8b758d762
    domain: switch
  mode: single

- id: auto_bathroom_lights
  alias: Auto off Bathroom Lights
  description: 'Turns off bathroom lights and mirror if they have been on for 3 hours.'
  triggers:
  - type: turned_on
    device_id: a7d4472c0a6c758d8bbb43b4dc91eb6d
    entity_id: 04992dcaacd7efec09815508abe801f5
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  - type: turned_on
    device_id: f66b45bd843d1b33f7dbe3dbb9d6ca42
    entity_id: 5e8d37f9c2f29122dcd7398dade809a2
    domain: switch
    trigger: device
    for:
      hours: 3
      minutes: 0
      seconds: 0
  actions:
  - type: turn_off
    device_id: a7d4472c0a6c758d8bbb43b4dc91eb6d
    entity_id: 04992dcaacd7efec09815508abe801f5
    domain: switch
  - type: turn_off
    device_id: f66b45bd843d1b33f7dbe3dbb9d6ca42
    entity_id: 5e8d37f9c2f29122dcd7398dade809a2
    domain: switch
  mode: single

- id: auto_off_bathroom_fan
  alias: Auto off Bathroom Fan
  description: 'Turns off the bathroom fan after 1 hour.'
  triggers:
  - type: turned_on
    device_id: bdb8e97f58ef83e2c04b622334b73ea9
    entity_id: 92a6b63bb20e5bf28c38ce0cccbc8f7a
    domain: switch
    trigger: device
    for:
      hours: 1
      minutes: 0
      seconds: 0
  conditions: []
  actions:
  - type: turn_off
    device_id: bdb8e97f58ef83e2c04b622334b73ea9
    entity_id: 92a6b63bb20e5bf28c38ce0cccbc8f7a
    domain: switch
  mode: single
