# Main bedroom

- alias: Main bedroom light switch
  id: j33namfxwh55
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 540d87ab8297c93f13f8d8afc230fbb8
      command: single
  action:
    service: switch.toggle
    entity_id: switch.main_bedroom_light

- alias: Main bedroom lights switch
  id: nkgorrj4tye9
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 540d87ab8297c93f13f8d8afc230fbb8
      command: double
  action:
    service: switch.toggle
    entity_id: switch.main_bedroom_lights

# - alias: Main bedroom light secondary switch
#   id: PAxvmiDnyWzL9
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 495fe74bc4bfa8fa49cca6091e18a17f
#       command: single
#   action:
#     service: switch.toggle
#     entity_id: switch.main_bedroom_light

# - alias: Main bedroom lights secondary switch
#   id: nkgorrj4tye1
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 495fe74bc4bfa8fa49cca6091e18a17f
#       command: double
#   action:
#     service: switch.toggle
#     entity_id: switch.main_bedroom_lights

# action:
#   - service: switch.turn_off
#     entity_id: switch.main_bedroom_light
#   - service: switch.turn_off
#     entity_id: switch.main_bedroom_salt_light
#   - service: switch.turn_off
#     entity_id: switch.main_standing_light

# - alias: Main bedroom salt light switch
#   id: C9QJhQFmrKa3
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 360598dfb6fcb29c405664e04c225df5
#       command: single
#   action:
#     service: switch.toggle
#     entity_id: switch.main_bedroom_salt_light

# - alias: Main standing light switch
#   id: zpa99yy4rlog
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 360598dfb6fcb29c405664e04c225df5
#       command: double
#   action:
#     service: switch.toggle
#     entity_id: switch.main_standing_light

# Secondary Bedroom

- alias: Secondary bedroom light switch
  id: mhz3qxge98wz
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: d78bce9fdbc85f5ed10b45516b83187a
      command: single
  action:
    service: switch.toggle
    entity_id: switch.secondary_bedroom_light

# Tertiary bedroom

- alias: Tertiary bedroom light switch
  id: iq02a357s9gr
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: bb2743894f2d6ae4b19e4414207d1075
      command: single
  action:
    service: switch.toggle
    entity_id: switch.tertiary_bedroom_light

# Living room

- alias: Living room light switch
  id: lqkvl3n7im71
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: e74d662fe4845b8e62b82b85676a4022
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.living_room_light

# Dining room

- alias: Dining room light switch
  id: ep1ehalevb6d
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: e74d662fe4845b8e62b82b85676a4022
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.dining_room_light

# Hallways

- alias: Upper hallway light A
  id: mnrb533c496s
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ad6ec388637fd6790bd38e29f68b87b5
      command: single
  action:
    service: switch.toggle
    entity_id: switch.upper_hallway_light_a

- alias: Upper hallway light B
  id: r93teyc350mb
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ad6ec388637fd6790bd38e29f68b87b5
      command: double
  action:
    service: switch.toggle
    entity_id: switch.upper_hallway_light_b

# Bathroom lights

- alias: Bathroom Lights
  id: cjecfw4v5x8g
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: a0b9e8430e4afb8b894dd09f9ca7ff5b
      command: right_single
  action:
    - service: switch.toggle
      entity_id: switch.bathroom_lights
    - service: switch.toggle
      entity_id: switch.bathroom_mirror_light

# Bathroom mirror duplicates

- alias: Bathroom Mirror Light (1)
  id: 7hk6uflp507r
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: a0b9e8430e4afb8b894dd09f9ca7ff5b
      command: right_double
  action:
    service: switch.toggle
    entity_id: switch.bathroom_mirror_light

- alias: Bathroom Mirror Light (2)
  id: a1rf91gu4y43
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: a0b9e8430e4afb8b894dd09f9ca7ff5b
      command: left_double
  action:
    service: switch.toggle
    entity_id: switch.bathroom_mirror_light

#  Bathroom Fan

- alias: Bathroom Fan
  id: 4vezdn7txjel
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: a0b9e8430e4afb8b894dd09f9ca7ff5b
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.bathroom_fan

#
# Turn off timer
#

- alias: Kitchen lights turn-off timer
  id: luns6ghe2lze
  trigger:
    platform: state
    entity_id: switch.kitchen_lights
    to: "on"
    for: "00:45:00"
  action:
    service: switch.turn_off
    entity_id: switch.kitchen_lights

- alias: Toilet lights turn-off timer
  id: luns6ahe2lze
  trigger:
    platform: state
    entity_id: switch.toilet_lights
    to: "on"
    for: "00:45:00"
  action:
    service: switch.turn_off
    entity_id: switch.toilet_lights

- alias: Upper hallway Lights A turn-off timer
  id: d692ybqbogqp
  trigger:
    platform: state
    entity_id: switch.upper_hallway_light_a
    to: "on"
    for: "08:00:00"
  action:
    - service: switch.toggle
      entity_id: switch.upper_hallway_light_a

- alias: Upper hallway Lights B turn-off timer
  id: d692ybq3ogqp
  trigger:
    platform: state
    entity_id: switch.upper_hallway_light_b
    to: "on"
    for: "01:00:00"
  action:
    - service: switch.toggle
      entity_id: switch.upper_hallway_light_b

- alias: Bathroom fan turn-off timer
  id: luns6gheylze
  trigger:
    platform: state
    entity_id: switch.bathroom_fan
    to: "on"
    for: "00:45:00"
  action:
    service: switch.turn_off
    entity_id: switch.bathroom_fan

- alias: Bathroom Lights turn-off timer
  id: x6h0qk8mw2hc
  trigger:
    platform: state
    entity_id: switch.bathroom_lights
    to: "on"
    for: "01:00:00"
  action:
    - service: switch.toggle
      entity_id: switch.bathroom_lights

- alias: Bathroom Mirror Light turn-off timer
  id: x6h0qk8mwehc
  trigger:
    platform: state
    entity_id: switch.bathroom_mirror_light
    to: "on"
    for: "01:00:00"
  action:
    - service: switch.toggle
      entity_id: switch.bathroom_mirror_light
