# Main bed - small switch

- alias: Main bedroom light
  id: FVYHeHUy8n2Hm
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 7b612f740196587aa9ca60bbaf6cb5de
      command: single
  action:
    service: switch.toggle
    entity_id: switch.main_bedroom_light

- alias: Main bedroom light (2)
  id: FVYHeEUy2n1Hm
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9f4548e756bbdf96d3edb491029788cc
      command: double
  action:
    service: switch.toggle
    entity_id: switch.main_bedroom_light

- alias: Main bedroom standing light
  id: v6FyMJGArp6
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 7b612f740196587aa9ca60bbaf6cb5de
      command: double
  action:
    service: switch.toggle
    entity_id: switch.standing_light_bed_main

- alias: Salt Light Bed Main
  id: Mn5DQAChe9l7ckM
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9f4548e756bbdf96d3edb491029788cc
      command: single
  action:
    service: switch.toggle
    entity_id: switch.salt_light_bed_main

- alias: Desk Light Bed Main
  id: VZkDHS4pnsJXYj5
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9f4548e756bbdf96d3edb491029788cc
      command: single
  action:
    service: switch.toggle
    entity_id: switch.desk_light_bed_main

# Main bed - big switch

# - alias: Stand Light Bed Main
#   id: y36uC65BaKr6PES
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 472f8404b23bf6b102b102474785e077
#       command: single
#   action:
#     service: switch.toggle
#     entity_id: switch.standing_light_bed_main

# - alias: Desk Light Bed Main (2)
#   id: R6utKVAW1EanVfT
#   trigger:
#     platform: event
#     event_type: zha_event
#     event_data:
#       device_id: 472f8404b23bf6b102b102474785e077
#       command: double
#   action:
#     service: switch.toggle
#     entity_id: switch.desk_light_bed_main

# Secondary bedroom

- alias: secondary bedroom light
  id: E2WxR2nR68xR
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 66daa7816b8276bb42c12fc936e86fe3
      command: single
  action:
    service: switch.toggle
    entity_id: switch.secondary_bedroom_light

# Tertiary bedroom

- alias: Tertiary bedroom light
  id: atUOL6c5M1g3
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 472f8404b23bf6b102b102474785e077
      command: single
  action:
    service: switch.toggle
    entity_id: switch.tertiary_bedroom_light

# Bathroom - double switch

- alias: Light Bath Main
  id: z6YdKe67uAZ787h
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ca65477b6f91da9350b8b0467683f2ab
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.light_bath_main

- alias: Mirror Bath Main
  id: 7hbK40dDe5nAMSJ
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ca65477b6f91da9350b8b0467683f2ab
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.mirror_bath_main

- alias: Mirror Bath Main (2)
  id: 2Sz8nNNSjQanNDN
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ca65477b6f91da9350b8b0467683f2ab
      command: right_double
  action:
    service: switch.toggle
    entity_id: switch.mirror_bath_main

- alias: Mirror Bath Main (3)
  id: 2Sf1nNNSjAanNDM
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ca65477b6f91da9350b8b0467683f2ab
      command: left_double
  action:
    service: switch.toggle
    entity_id: switch.mirror_bath_main

- alias: Fan Bath Main
  id: 27jl0nAnpmUxjZF
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ca65477b6f91da9350b8b0467683f2ab
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.fan_bath_main

# 2nd floor Hallway switch

- alias: 2nd floor Hallway switch
  id: Rrquh6XU55NTiv0
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: d73b2e6ec6e6b26cb843081bb6358ffd
      command: single
  action:
    service: switch.toggle
    entity_id: switch.lights_floor_2_hallway

- alias: 2nd floor Hallway switch 2
  id: 3zF2zYK3qtXyF4
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: d73b2e6ec6e6b26cb843081bb6358ffd
      command: double
  action:
    service: switch.toggle
    entity_id: switch.lights_2_floor_2_hallway

# 1st floor living room

- alias: Main light living room
  id: lbqe6h429iwdd0
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 8fa3028d784f5e7a5a08f0e85f3d36df
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.main_living_room_light

- alias: Second light living room
  id: s6puuui0og220h
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 8fa3028d784f5e7a5a08f0e85f3d36df
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.second_living_room_light
