# Master badroom

- alias: Main bedroom light switch
  id: j33namfxwh55
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9d994506ad0dd4863fa3bc326677739a
      command: single
  action:
    service: switch.toggle
    entity_id: switch.master_bedroom_light

- alias: Main bedroom secondary light switch
  id: zpa99yy4rlog
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 360598dfb6fcb29c405664e04c225df5
      command: single
  action:
    service: switch.toggle
    entity_id: switch.master_bedroom_light

# Secondary Bedroom

- alias: Secondary bedroom light switch
  id: mhz3qxge98wz
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 788a57b676e259c0159d5f17dbb9d751
      command: single
  action:
    service: switch.toggle
    entity_id: switch.secondary_bedroom_light

# Tertiary bedroom

- alias: Tertiary bedroom light switch
  id: iq02a357s9gr
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: ad9b3b770878b0693ab8a99bb0a25946
      command: single
  action:
    service: switch.toggle
    entity_id: switch.tertiary_bedroom_light

# Living room

- alias: Living room light switch
  id: lqkvl3n7im71
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 322093adb226b43517955621d1c95e8c
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.living_room_light

# Dining room

- alias: Dining room light switch
  id: ep1ehalevb6d
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 322093adb226b43517955621d1c95e8c
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.dining_room_light

# Hallways

- alias: Upper hallway light A
  id: mnrb533c496s
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9b14b1042b29c21fa02c4c91829283ee
      command: single
  action:
    service: switch.toggle
    entity_id: switch.upper_hallway_light_a

- alias: Upper hallway light B
  id: r93teyc350mb
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 9b14b1042b29c21fa02c4c91829283ee
      command: double
  action:
    service: switch.toggle
    entity_id: switch.upper_hallway_light_b

# Bathroom

- alias: Bathroom Lights
  id: cjecfw4v5x8g
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 1193c2c9517b67eaa202b5a75a9e8c57
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.bathroom_lights

- alias: Bathroom Mirror Light
  id: d692ybqbogqp
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 1193c2c9517b67eaa202b5a75a9e8c57
      command: right_single
  action:
    service: switch.toggle
    entity_id: switch.bathroom_mirror_light

- alias: Bathroom Mirror Light (1)
  id: 7hk6uflp507r
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 1193c2c9517b67eaa202b5a75a9e8c57
      command: right_double
  action:
    service: switch.toggle
    entity_id: switch.bathroom_mirror_light

- alias: Bathroom Mirror Light (2)
  id: a1rf91gu4y43
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 1193c2c9517b67eaa202b5a75a9e8c57
      command: left_double
  action:
    service: switch.toggle
    entity_id: switch.bathroom_mirror_light

- alias: Bathroom Fan
  id: 4vezdn7txjel
  trigger:
    platform: event
    event_type: zha_event
    event_data:
      device_id: 1193c2c9517b67eaa202b5a75a9e8c57
      command: left_single
  action:
    service: switch.toggle
    entity_id: switch.bathroom_fan
