# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

frontend:

mqtt:
  client_id: home-assistant-1
  broker: 192.168.68.116
  port: 1883
  username: admin
  password: TpHYvDJHR96nsfY

switch:
  - platform: mqtt
    name: "Main living room light"
    command_topic: "cmnd/main_living_room_light/power"
    state_topic: "stat/main_living_room_light/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Second living room light"
    command_topic: "cmnd/second_living_room_light/power"
    state_topic: "stat/second_living_room_light/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Main bedroom light"
    command_topic: "cmnd/main_bedroom_light/power"
    state_topic: "stat/main_bedroom_light/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Desk Light Bed-main"
    command_topic: "cmnd/desk_light_bed_main/power"
    state_topic: "stat/desk_light_bed_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Standing Light Bed-main"
    command_topic: "cmnd/standing_light_bed_main/power"
    state_topic: "stat/standing_light_bed_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Salt Light Bed-main"
    command_topic: "cmnd/salt_light_bed_main/power"
    state_topic: "stat/salt_light_bed_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Secondary bedroom light"
    command_topic: "cmnd/secondary_bedroom_light/power"
    state_topic: "stat/secondary_bedroom_light/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Tertiary bedroom light"
    command_topic: "cmnd/tertiary_bedroom_light/power"
    state_topic: "stat/tertiary_bedroom_light/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Fan Bath-main"
    command_topic: "cmnd/fan_bath_main/power"
    state_topic: "stat/fan_bath_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Light Bath-main"
    command_topic: "cmnd/light_bath_main/power"
    state_topic: "stat/light_bath_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Mirror Bath-main"
    command_topic: "cmnd/mirror_bath_main/power"
    state_topic: "stat/mirror_bath_main/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Lights Floor-2 Hallway"
    command_topic: "cmnd/lights_floor_2_hallway/power"
    state_topic: "stat/lights_floor_2_hallway/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true

  - platform: mqtt
    name: "Lights 2 Floor-2 Hallway"
    command_topic: "cmnd/lights_2_floor_2_hallway/power"
    state_topic: "stat/lights_2_floor_2_hallway/POWER"
    qos: 1
    payload_on: "ON"
    payload_off: "OFF"
    retain: true
